name: Release npm-package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version tag'
        required: true
        type: string
  defaults:
    run:
      working-directory: npm-package

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print the version to STDOUT
        run: echo  The version you want to release is ${{ inputs.version }}
      - name: Set the version in package.json
        run: npm version ${{ inputs.version }}
      - name: Push scoped tag
        run: |
          git commit -am "release: Release new version"
          git tag npm-package_${{ inputs.version }}
          git push origin npm-package_${{ inputs.version }}
